- name: KAFKA | Install
  import_tasks: kafka-install.yml
  tags:
    - kafka_install

- name: KAFKA | Configure
  import_tasks: kafka-config.yml
  tags:
    - kafka_configure

- name: KAFKA | Service
  import_tasks: kafka-service.yml
  tags:
    - kafka_service