FROM maven:3.6-jdk-8-slim as maven
COPY ./pom.xml ./pom.xml
COPY ./src ./src
RUN mvn dependency:go-offline -B
RUN mvn package -DskipTests

FROM openjdk:8-jre-slim
ARG jar=qucosa-sitemaps-*.jar

WORKDIR /app
COPY ./app-run.sh ./app-run.sh
RUN chmod -x ./app-run.sh

COPY --from=maven target/$jar ./qucosa-sitemaps.jar

RUN mkdir log

ENTRYPOINT ["sh", "./app-run.sh"]

EXPOSE 8082