version: '2.0'

services:
  db:
    container_name: qucosa-sitemap-db
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    ports:
      - "4721:5432"
    environment:
      POSTGRES_PASSWORD: sitemap
      POSTGRES_USER: sitemap
      POSTGRES_DB: qucosa_sitemap

  app:
    container_name: qucosa-sitemap
    build:
      context: .
      dockerfile: ./Dockerfile.sitemap
    ports:
      - "8080:8080"
    networks:
      - default
    links:
        - db:db
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:5432
