# install java (default-java = openjdk8)
- name: Update packet manager
  apt:
    update_cache: yes

- name: Install java openjdk8
  package: "name={{ java_packages }} state=present"
  when: java_rpm_install == false

- name: config java
  alternatives:
    name: java
    path: /usr/lib/jvm/default-java/bin/java

- name: set JAVA_HOME
  lineinfile: 
    dest: /etc/environment
    state: present
    regexp: '^JAVA_HOME'
    line: 'JAVA_HOME=/usr/lib/jvm/default-java'

- name: copy java oracle
  copy:
    src: "{{ java_rpm }}"
    dest: /tmp/{{ java_rpm }}
    mode: 0755
  when: java_rpm_install == true

- name: install java oracle
  yum: name=/tmp/{{ java_rpm }}
  when: java_rpm_install == true

# install maven, git and postgresql-db
- name: install maven and git
#  become: yes
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - maven
    - git
    - postgresql
    - postgresql-contrib
    - python-psycopg2

# checkout/build/package sitemap maven project
- git:
    repo: 'https://github.com/qucosa/qucosa-sitemaps.git'
    dest: "{{ project_directory }}"
    force: yes

- name: build project qucosa-sitemap-REST-service
#  become: yes
  shell: |
    cd {{ project_directory }}
    mvn clean package

- git:
    repo: "https://{{ gitlab_user }}:{{ gitlab_pw }}@git.slub-dresden.de/tolksdorf/qucosa-sitemap-feeder.git"
    dest: "{{ project_directory2 }}"
    force: yes

- name: build project qucosa-sitemap-feeder
  shell: |
    cd {{ project_directory2 }}
    mvn clean package

#- name: set owner for directory
#  become: yes
#  file:
#    path: /home/tolksdorf/qucosa-sitemaps
#    owner: tolksdorf
#    group: tolksdorf
#    mode: 0755
#    recurse: yes

- name: setup postgresql-db
  postgresql_db:
    name: qucosa_sitemap
#    login_user: qucosa
#    login_password: qucosa
    encoding: UTF-8
    lc_collate: en_US.utf8
    lc_ctype: en_US.utf8
    template: template0
  become: yes
  become_user: postgres

- name: setup postgresql-user
  become: yes
  become_user: postgres
  postgresql_user:
    name: qucosa
    password: qucosa
    db: qucosa_sitemap
    priv: ALL
#    role_attr_flags: CREATEDB

