# install java (default-java = openjdk8)
- name: Update packet manager
  apt:
    update_cache: yes

- name: Install java openjdk8
  package: "name={{ java_packages }} state=present"
  when: java_rpm_install == false

- name: config java
  alternatives:
    name: java
    path: /usr/lib/jvm/default-java/bin/java

- name: set JAVA_HOME
  lineinfile: 
    dest: /etc/environment
    state: present
    regexp: '^JAVA_HOME'
    line: 'JAVA_HOME=/usr/lib/jvm/default-java/bin'

- name: copy java oracle
  copy:
    src: "{{ java_rpm }}"
    dest: /tmp/{{ java_rpm }}
    mode: 0755
  when: java_rpm_install == true

- name: install java oracle
  yum: name=/tmp/{{ java_rpm }}
  when: java_rpm_install == true

# install maven, git and postgresql-db and checkout/build/package sitemap maven project
- name: install maven and git
  become: yes
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - maven
    - git
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- git:
    repo: 'https://github.com/qucosa/qucosa-sitemaps.git'
    dest: /home/tolksdorf/qucosa-sitemaps
    force: yes

- name: build project
  become: yes
  shell: |
    cd /home/tolksdorf/qucosa-sitemaps
    mvn clean package

- name: set owner for directory
  become: yes
  file:
    path: /home/tolksdorf/qucosa-sitemaps
    owner: tolksdorf
    group: tolksdorf
    mode: 0755
    recurse: yes

- name: setup postgresql-user
  become: yes
#  become_user: postgres
  postgresql_user:
    name: qucosa
    password: qucosa
    role_attr_flags: CREATEDB

- name: setup postgresql-db
  become: yes
  postgresql_db:
    name: qucosa_sitemap
    login_user: qucosa
    login_password: qucosa
    encoding: UTF-8
    lc_collate: en_US.utf8
    lc_ctype: en_US.utf8
    template: template0
