- name: restart zookeeper
  systemd:
    name: zookeeper
    state: restarted
  when: kafka_service_state != 'stopped'

- name: restart kafka
  systemd:
    name: kafka
    state: restarted
  when: kafka_service_state != 'stopped'

