- name: Setup machine with java/maven/git and the project
  hosts: "{{ host }}"
  remote_user: "{{ ssh_user }}"
  become: yes
  vars:
    project_directory: /tmp/qucosa-sitemaps
    project_directory2: /tmp/qucosa-sitemap-feeder
  roles:
    - java

- name: deploy springboot-sitemapservice as daemon/service
  hosts: "{{ host }}"
  remote_user: "{{ ssh_user }}"
  become: yes
  vars:
    project_directory: /tmp/qucosa-sitemaps
    springboot_application_name: qucosa-sitemaps
    springboot_src_file: "{{ project_directory }}/target/qucosa-sitemaps-1.0-SNAPSHOT.jar"
    springboot_propertyfile_template: "/tmp/{{ springboot_application_name }}/src/main/resources/{{ application_properties_file }}"
    springboot_user: sitemapservice
    springboot_group: sitemapservice
  roles:
    - ansible-springboot

- name: deploy kafka/zookeeper as service
  hosts: "{{ host }}"
  remote_user: "{{ ssh_user }}"
  become: yes
  roles:
    - kafka

- name: deploy camel-kafka-sitemap-feeder
  hosts: "{{ host }}"
  remote_user: "{{ ssh_user }}"
  become: yes
  vars:
    project_directory: /tmp/qucosa-sitemap-feeder
    springboot_application_name: qucosa-sitemap-feeder
    springboot_src_file: "{{ project_directory }}/target/qucosa-sitemap-feeder-1.0-SNAPSHOT.jar"
    springboot_propertyfile_template: "/tmp/{{ springboot_application_name }}/src/main/resources/{{ application_properties_file }}"
    springboot_user: sitemapservice
    springboot_group: sitemapservice
  roles:
    - ansible-springboot

