- name: java
#  hosts: sitemapvm
  hosts: sitemapapp04
  remote_user: tolksdorf
  become: yes
  roles:
    - java

- name: deploy springboot-sitemapservice as daemon/service
#  hosts: sitemapvm
  hosts: sitemapapp04
  remote_user: tolksdorf
  become: yes
#  become_user: restservice
#  become_method: su
  vars:
    springboot_application_name: qucosa-sitemaps
    springboot_src_file: /home/vagrant/qucosa-sitemaps/target/qucosa-sitemaps-1.0-SNAPSHOT.jar
    springboot_user: tolksdorf
    springboot_group: tolksdorf
  roles:
    - ansible-springboot

